### ISSUE TITLE
Content in Role_Mapping.adoc needs to be rewritten to apply to SB

### ISSUE THREAD

**Issue by roldanbob** [teiid/teiid-documents#145]
At the end of this first paragraph of Role_Mapping.adoc, it state that _"The kit includes example files for use with the UsersRolesLoginModule - see teiid-security-roles.properties."_

This content is currently included as part of the SB version of the guide. Per Ramesh, in Openshift Keycloak is the security domain provider, so the wording does not apply in the Spring Boot world.

**Comment by shawkins** [comment]
You are correct.  This has been updated to only mention security domains for wildfly.
