### ISSUE TITLE
how to use the PostgreSQL protocol access VDB?

### ISSUE THREAD

**Issue by wangg0925** [teiid/teiid-documents#174]
Once VDB is deployed, your VDB can be accessed through Teiid JDBC-SQL, the PostgreSQL protocol, OData, or REST.

So, how to use the PostgreSQL protocol access VDB?

**Comment by shawkins** [comment]
By default the pg port is 35432 - see the chapters in the client developers guide for more on configuring specific clients / applications http://teiid.github.io/teiid-documents/master/content/client-dev/Client_Developers_Guide.html
