### ISSUE TITLE
The Teiid Console page is missing images

### ISSUE THREAD

**Issue by pmcelreavy** [teiid/teiid-documents#65]
Section "Profile View" links to image "images/author/download/attachments/18646076/webconsole2.png"

Section "Runtime View" links to image "images/author/download/attachments/18646076/webconsole1.png"

Both these images are missing.

**Comment by rareddy** [comment]
Can you log a JIRA for this please? May be when moving the docbook they got misplaced

**Comment by pmcelreavy** [comment]
I do not know of this JIRA...

**Comment by rareddy** [comment]
create a issue here https://issues.jboss.org/browse/TEIID

**Comment by pmcelreavy** [comment]
Logged: https://github.com/teiid/teiid-documents/issues/65
